AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Simple Email App

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  StudentMessagingServiceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: "StudentMessagingService::StudentMessagingService.Function::FunctionHandler"
      Runtime: dotnetcore3.1
      CodeUri: ''
      MemorySize: 256
      Timeout: 30
      Role: arn:aws:iam::423319894549:role/student_messaging_service_role


# Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # StudentMessagingServiceApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  # StudentMessagingServiceFunction:
  #   Description: "Hello World Lambda Function ARN"
  #   Value: !GetAtt StudentMessagingServiceFunction.Arn
  # StudentMessagingServiceFunctionIamRole:
  #   Description: "Implicit IAM Role created for Hello World function"
  #   Value: !GetAtt StudentMessagingServiceFunctionRole.Arn
